version: '3.9'
services:
  redis:
    build: ./redis-db/.
    container_name: catch_game_db
    restart: unless-stopped
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - catch_game_network
    # ports:
    #   - "6379:6379"

  express-api:
    build: ./express-api/.
    container_name: catch_game_api
    restart: unless-stopped
    volumes:
      - ./express-api:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - .env
    networks:
      - catch_game_network
    depends_on:
      - redis

  react-fe:
    build: ./react-fe/.
    container_name: catch_game_fe
    restart: unless-stopped
    volumes:
      - ./react-fe:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - express-api

networks:
  catch_game_network:
    driver: bridge

volumes:
  redis_data:
